from cellInBounds import cellInBoundsTests
from countLiveNeighbors import countLiveNeighborsTests
from nextBoardState import nextBoardStateTests

cellInBoundsTests()
countLiveNeighborsTests()
nextBoardStateTests()